name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 4.193.177.148
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Reddit-Clone
            git pull origin main
            # 1. Stop and remove existing containers/networks
            # docker compose down
            # 2. Build from scratch ignoring cache and start up
            # docker compose build --no-cache
            docker compose up -d --build
            # 3. Optional: Remove unused images to save disk space
            # docker image prune -f
